/*******************************************************************************
 * Import pipeline libraries
 *******************************************************************************/
@Library(['eis-jenkins-lib@develop']) _

pipeline {

        agent {
            label 'java'
        }

        options {
            ansiColor('xterm')
        }

        triggers {
            pollSCM 'H H 1 12 *'
        }

        stages {
            stage('Build'){
                steps{
                    eisMavenExecute(
                        goal: "clean install -DskipTests=true"
                    )
                    script {
                        notifyBitbucket()
                    }
                }

            }

            stage('Test'){
                steps {
                    eisMavenExecute(
                        goal: "test"
                    )
                    sh 'ls -alF target/'
                    script {
                        notifyBitbucket()
                    }
                }

            }

            stage('Deploy'){
                when {
                   branch 'develop'
                }
                steps {
                    eisMavenExecute(
                        goal: "deploy -DskipTests=true"
                    )
                    script {
                        notifyBitbucket()
                    }
                }
            }
        }

        post {
            always {
                archiveArtifacts artifacts: 'target/surefire-reports/**/*'
                junit testResults: 'target/surefire-reports/*.xml'

                script {
                    currentBuild.result = currentBuild.result ?: 'SUCCESS'
                    notifyBitbucket()
                }
            }

            failure {
                sendEmail("mahesh.gummaraju@eastspring.com")
            }

        }
}

