#https://jira.intranet.asia/browse/TOM-5178

# ===================================================================================================================================================================================
# Date            JIRA        Comments
# ===================================================================================================================================================================================
# 20/09/2019      TOM-5178    Additional data fields to be exposed to CORIC Outbound files
# 19/11/2020      EISDEV-7166  Input Layout Changes for BNP L1 file for 37 columns
# 22/12/2020      EISDEV-5173 Change in input file date format
# ===================================================================================================================================================================================

#https://collaborate.intranet.asia/display/TOM/Performance+Data+Mart+-New

@dw_interface_performance
@dmp_dw_regression
@tom_5178 @tom_5178_inbound @perf_l1 @eisdev_7166 @eisdev_5173
Feature: Test BNP performance L1 file for verification of 12 additional columns added as below

  1. 6 Month Net Absolute Returns - Primary Benchmark
  2.  6 Month Net Absolute Returns - Secondary Benchmark
  3.  6 Month Net Relative Returns - Primary Benchmark
  4.  1 Month Benchmark Returns - Secondary Benchmark
  5.  3 Month Benchmark Returns - Secondary Benchmark
  6.  6 Month Benchmark Returns - Secondary Benchmark
  7.  1 Year Benchmark Returns - Secondary Benchmark
  8.  1 Month Gross Relative Returns - Secondary Benchmark
  9.  3 Month Gross Relative Returns - Secondary Benchmark
  10. 6 Month Gross Relative Returns - Secondary Benchmark
  11. 1 Year Gross Relative Returns - Secondary Benchmark
  12.  Since Inception Gross Absolute Returns - Primary Benchmark
  13.  Since Inception Gross Absolute Returns - Secondary Benchmark
  14.  Since Inception Gross Relative Returns - Primary Benchmark

  Background:

    Given I set the DMP workflow web service endpoint to named configuration "dwh.ws.WORKFLOW"
    And I set the database connection to configuration "dmp.db.DW"
    And I generate value with date format "YYYYMMdd-HHmmss" and assign to variable "UPDATE_VAR_SYSDATE"

  Scenario: Clear old test data and setup variables

    Given I assign "tests/test-data/dmp-interfaces/Reporting/PerformanceL1/Inbound" to variable "testdata.path"

    #In order to make feature file re-runnable, existing fund performance & related data is cleaned up
    And I execute below query
    """
     ${testdata.path}/sql/Additional_Columns_AccountBMSetup.sql
    """

  Scenario: Load BNP L1 performance file having 6 records

    Given I copy files below from local folder "${testdata.path}/testdata" to the host "dmp.ssh.inbound" folder "${dmp.ssh.inbound.path}":
      | PERFL1_Additional_Columns.csv |

    And I process files with below parameters and wait for the job to be completed
      | BUSINESS_FEED |                               |
      | FILE_PATTERN  | PERFL1_Additional_Columns.csv |
      | MESSAGE_TYPE  | EIS_MT_BNP_DWH_PERF_L1        |

    Then I extract new job id from jblg table into a variable "JOB_ID"

    And I expect value of column "JBLG_ROW_COUNT" in the below SQL query equals to "1":
    """
      SELECT COUNT(1) AS JBLG_ROW_COUNT FROM FT_T_JBLG WHERE JOB_ID = '${JOB_ID}' AND TASK_SUCCESS_CNT ='6'
    """

  Scenario: Perform checks in WCRI for multiple scenarios

    Then I expect value of column "WCRI_COUNT" in the below SQL query equals to "28":
    """
      SELECT COUNT(*) AS WCRI_COUNT
      FROM FT_T_WCRI WHERE ACCT_SOK = (select acct_sok from ft_t_wact where intrnl_id10 = 'TOM5178' and  DW_STATUS_NUM =1) AND DW_STATUS_NUM =1
    """

  Scenario Outline: Verify the data uploaded in column <Column>

    Then I expect value of column "<Column>" in the below SQL query equals to "PASS":
    """
      <Query>
    """

    Examples: Data Verifications having value not zero
      | Column                                        | Query                                                                                                                                                                                                                                                                                                                                  |
      #6 Month Net Absolute Returns - Primary Benchmark
      | M6FundNetAbsoluteReturn_1                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFeesOrWthdgTaxes' and RETURN_6M_CAMT='13.1'                          |
      | M6FundNetAbsoluteReturn_2                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_2 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFees' and RETURN_6M_CAMT='13.2'                                      |
      | M6FundNetAbsoluteReturn_3                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossMgtFees' and RETURN_6M_CAMT='13.3'                                      |
      | M6FundNetAbsoluteReturn_4                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRRGrossTWRR' and RETURN_6M_CAMT='13.4'                                        |
      | M6FundNetAbsoluteReturn_5                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAV' and RETURN_6M_CAMT='13.5'                                                  |
      | M6FundNetAbsoluteReturn_6                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_6 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRR' and RETURN_6M_CAMT='13.6'                                                 |

      #6 Month Net Absolute Returns - Secondary Benchmark
      | M6FundNetAbsoluteReturn_7                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_7 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFeesOrWthdgTaxes' and RETURN_6M_CAMT='13.1'                        |
      | M6FundNetAbsoluteReturn_8                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_8 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFees' and RETURN_6M_CAMT='13.2'                                    |
      | M6FundNetAbsoluteReturn_9                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_9 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossMgtFees' and RETURN_6M_CAMT='13.3'                                    |
      | M6FundNetAbsoluteReturn_10                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_10 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRRGrossTWRR' and RETURN_6M_CAMT='13.4'                                     |
      | M6FundNetAbsoluteReturn_11                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_11 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAV' and RETURN_6M_CAMT='13.5'                                               |
      | M6FundNetAbsoluteReturn_12                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetAbsoluteReturn_12 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRR' and RETURN_6M_CAMT='13.6'                                              |

      #6 Month Net Relative Returns - Primary Benchmark
      | M6FundNetRelativeReturn_1                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetRelativeReturn_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFeesOrWthdgTaxes' and RELV_RETURN_6M_CAMT='14.1'                     |
      | M6FundNetRelativeReturn_2                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetRelativeReturn_2 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFees' and RELV_RETURN_6M_CAMT='14.2'                                 |
      | M6FundNetRelativeReturn_3                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetRelativeReturn_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossMgtFees' and RELV_RETURN_6M_CAMT='14.3'                                 |
      | M6FundNetRelativeReturn_4                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetRelativeReturn_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRRGrossTWRR' and RELV_RETURN_6M_CAMT='14.4'                                   |
      | M6FundNetRelativeReturn_5                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetRelativeReturn_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAV' and RELV_RETURN_6M_CAMT='14.5'                                             |
      | M6FundNetRelativeReturn_6                     | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundNetRelativeReturn_6 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRR' and RELV_RETURN_6M_CAMT='14.6'                                            |

      #1 Month Benchmark Returns - Secondary Benchmark
      | M1FundSecBenchmarkReturn_1                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and ACCT_2_RETURN_1M_CAMT='1.1'                       |
      | M1FundSecBenchmarkReturn_3                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFeesOrWthdgTaxes' and ACCT_2_RETURN_1M_CAMT='1.1'                 |
      | M1FundSecBenchmarkReturn_4                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFees' and ACCT_2_RETURN_1M_CAMT='1.2'                             |
      | M1FundSecBenchmarkReturn_5                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and ACCT_2_RETURN_1M_CAMT='1.2'                                   |
      | M1FundSecBenchmarkReturn_7                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_7 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and ACCT_2_RETURN_1M_CAMT='1.3'                                   |
      | M1FundSecBenchmarkReturn_8                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_8 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossMgtFees' and ACCT_2_RETURN_1M_CAMT='1.3'                             |
      | M1FundSecBenchmarkReturn_10                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_10 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and ACCT_2_RETURN_1M_CAMT='1.4'                                     |
      | M1FundSecBenchmarkReturn_12                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_12 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRRGrossTWRR' and ACCT_2_RETURN_1M_CAMT='1.4'                              |
      | M1FundSecBenchmarkReturn_14                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_14 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAV' and ACCT_2_RETURN_1M_CAMT='1.5'                                        |
      | M1FundSecBenchmarkReturn_15                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_15 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRR' and ACCT_2_RETURN_1M_CAMT='1.6'                                       |
      | M1FundSecBenchmarkReturn_17                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundSecBenchmarkReturn_17 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and ACCT_2_RETURN_1M_CAMT='1.6'                           |

      #3 Month Benchmark Returns - Secondary Benchmark
      | M3FundSecBenchmarkReturn_1                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and ACCT_2_RETURN_3M_CAMT='3.1'                       |
      | M3FundSecBenchmarkReturn_3                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFeesOrWthdgTaxes' and ACCT_2_RETURN_3M_CAMT='3.1'                 |
      | M3FundSecBenchmarkReturn_4                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFees' and ACCT_2_RETURN_3M_CAMT='3.2'                             |
      | M3FundSecBenchmarkReturn_5                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and ACCT_2_RETURN_3M_CAMT='3.2'                                   |
      | M3FundSecBenchmarkReturn_7                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_7 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and ACCT_2_RETURN_3M_CAMT='3.3'                                   |
      | M3FundSecBenchmarkReturn_8                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_8 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossMgtFees' and ACCT_2_RETURN_3M_CAMT='3.3'                             |
      | M3FundSecBenchmarkReturn_10                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_10 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and ACCT_2_RETURN_3M_CAMT='3.4'                                     |
      | M3FundSecBenchmarkReturn_12                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_12 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRRGrossTWRR' and ACCT_2_RETURN_3M_CAMT='3.4'                              |
      | M3FundSecBenchmarkReturn_14                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_14 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAV' and ACCT_2_RETURN_3M_CAMT='3.5'                                        |
      | M3FundSecBenchmarkReturn_15                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_15 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRR' and ACCT_2_RETURN_3M_CAMT='3.6'                                       |
      | M3FundSecBenchmarkReturn_17                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundSecBenchmarkReturn_17 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and ACCT_2_RETURN_3M_CAMT='3.6'                           |

      #6 Month Benchmark Returns - Secondary Benchmark
      | M6FundSecBenchmarkReturn_1                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and ACCT_2_RETURN_6M_CAMT='5.1'                       |
      | M6FundSecBenchmarkReturn_3                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFeesOrWthdgTaxes' and ACCT_2_RETURN_6M_CAMT='5.1'                 |
      | M6FundSecBenchmarkReturn_4                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFees' and ACCT_2_RETURN_6M_CAMT='5.2'                             |
      | M6FundSecBenchmarkReturn_5                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and ACCT_2_RETURN_6M_CAMT='5.2'                                   |
      | M6FundSecBenchmarkReturn_7                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_7 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and ACCT_2_RETURN_6M_CAMT='5.3'                                   |
      | M6FundSecBenchmarkReturn_8                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_8 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossMgtFees' and ACCT_2_RETURN_6M_CAMT='5.3'                             |
      | M6FundSecBenchmarkReturn_10                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_10 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and ACCT_2_RETURN_6M_CAMT='5.4'                                     |
      | M6FundSecBenchmarkReturn_12                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_12 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRRGrossTWRR' and ACCT_2_RETURN_6M_CAMT='5.4'                              |
      | M6FundSecBenchmarkReturn_14                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_14 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAV' and ACCT_2_RETURN_6M_CAMT='5.5'                                        |
      | M6FundSecBenchmarkReturn_15                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_15 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRR' and ACCT_2_RETURN_6M_CAMT='5.6'                                       |
      | M6FundSecBenchmarkReturn_17                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundSecBenchmarkReturn_17 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and ACCT_2_RETURN_6M_CAMT='5.6'                           |

      #1 Year Benchmark Returns - Secondary Benchmark
      | Y1FundSecBenchmarkReturn_1                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and CUM_1YR_ACCT_2_RET_CAMT='7.1'                     |
      | Y1FundSecBenchmarkReturn_3                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFeesOrWthdgTaxes' and CUM_1YR_ACCT_2_RET_CAMT='7.1'               |
      | Y1FundSecBenchmarkReturn_4                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossAllFees' and CUM_1YR_ACCT_2_RET_CAMT='7.2'                           |
      | Y1FundSecBenchmarkReturn_5                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and CUM_1YR_ACCT_2_RET_CAMT='7.2'                                 |
      | Y1FundSecBenchmarkReturn_7                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_7 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and CUM_1YR_ACCT_2_RET_CAMT='7.3'                                 |
      | Y1FundSecBenchmarkReturn_8                    | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_8 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAVGrossMgtFees' and CUM_1YR_ACCT_2_RET_CAMT='7.3'                           |
      | Y1FundSecBenchmarkReturn_10                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_10 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and CUM_1YR_ACCT_2_RET_CAMT='7.4'                                   |
      | Y1FundSecBenchmarkReturn_12                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_12 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRRGrossTWRR' and CUM_1YR_ACCT_2_RET_CAMT='7.4'                            |
      | Y1FundSecBenchmarkReturn_14                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_14 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetNAV' and CUM_1YR_ACCT_2_RET_CAMT='7.5'                                      |
      | Y1FundSecBenchmarkReturn_15                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_15 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='NetTWRR' and CUM_1YR_ACCT_2_RET_CAMT='7.6'                                     |
      | Y1FundSecBenchmarkReturn_17                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundSecBenchmarkReturn_17 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and CUM_1YR_ACCT_2_RET_CAMT='7.6'                         |

      #1 Month Gross Relative Returns - Secondary Benchmark
      | M1FundGrossRelativeReturnSecondaryBenchmark_1 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundGrossRelativeReturnSecondaryBenchmark_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and RELV_RETURN_1M_CAMT='2.1'      |
      | M1FundGrossRelativeReturnSecondaryBenchmark_2 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundGrossRelativeReturnSecondaryBenchmark_2 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and RELV_RETURN_1M_CAMT='2.2'                  |
      | M1FundGrossRelativeReturnSecondaryBenchmark_3 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundGrossRelativeReturnSecondaryBenchmark_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and RELV_RETURN_1M_CAMT='2.3'                  |
      | M1FundGrossRelativeReturnSecondaryBenchmark_4 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundGrossRelativeReturnSecondaryBenchmark_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and RELV_RETURN_1M_CAMT='2.4'                     |
      | M1FundGrossRelativeReturnSecondaryBenchmark_5 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M1FundGrossRelativeReturnSecondaryBenchmark_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and RELV_RETURN_1M_CAMT='2.6'           |

      #3 Month Gross Relative Returns - Secondary Benchmark
      | M3FundGrossRelativeReturnSecondaryBenchmark_1 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundGrossRelativeReturnSecondaryBenchmark_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and RELV_RETURN_3M_CAMT='4.1'      |
      | M3FundGrossRelativeReturnSecondaryBenchmark_2 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundGrossRelativeReturnSecondaryBenchmark_2 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and RELV_RETURN_3M_CAMT='4.2'                  |
      | M3FundGrossRelativeReturnSecondaryBenchmark_3 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundGrossRelativeReturnSecondaryBenchmark_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and RELV_RETURN_3M_CAMT='4.3'                  |
      | M3FundGrossRelativeReturnSecondaryBenchmark_4 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundGrossRelativeReturnSecondaryBenchmark_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and RELV_RETURN_3M_CAMT='4.4'                     |
      | M3FundGrossRelativeReturnSecondaryBenchmark_5 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M3FundGrossRelativeReturnSecondaryBenchmark_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and RELV_RETURN_3M_CAMT='4.6'           |

      #6 Month Gross Relative Returns - Secondary Benchmark
      | M6FundGrossRelativeReturnSecondaryBenchmark_1 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundGrossRelativeReturnSecondaryBenchmark_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and RELV_RETURN_6M_CAMT='6.1'      |
      | M6FundGrossRelativeReturnSecondaryBenchmark_2 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundGrossRelativeReturnSecondaryBenchmark_2 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and RELV_RETURN_6M_CAMT='6.2'                  |
      | M6FundGrossRelativeReturnSecondaryBenchmark_3 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundGrossRelativeReturnSecondaryBenchmark_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and RELV_RETURN_6M_CAMT='6.3'                  |
      | M6FundGrossRelativeReturnSecondaryBenchmark_4 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundGrossRelativeReturnSecondaryBenchmark_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and RELV_RETURN_6M_CAMT='6.4'                     |
      | M6FundGrossRelativeReturnSecondaryBenchmark_5 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS M6FundGrossRelativeReturnSecondaryBenchmark_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and RELV_RETURN_6M_CAMT='6.6'           |

      #1 Year Gross Relative Returns - Secondary Benchmark
      | Y1FundGrossRelativeReturnSecondaryBenchmark_1 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundGrossRelativeReturnSecondaryBenchmark_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and CUM_1YR_RELV_RETURN_CAMT='8.1' |
      | Y1FundGrossRelativeReturnSecondaryBenchmark_2 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundGrossRelativeReturnSecondaryBenchmark_2 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and CUM_1YR_RELV_RETURN_CAMT='8.2'             |
      | Y1FundGrossRelativeReturnSecondaryBenchmark_3 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundGrossRelativeReturnSecondaryBenchmark_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and CUM_1YR_RELV_RETURN_CAMT='8.3'             |
      | Y1FundGrossRelativeReturnSecondaryBenchmark_4 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundGrossRelativeReturnSecondaryBenchmark_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and CUM_1YR_RELV_RETURN_CAMT='8.4'                |
      | Y1FundGrossRelativeReturnSecondaryBenchmark_5 | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS Y1FundGrossRelativeReturnSecondaryBenchmark_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and CUM_1YR_RELV_RETURN_CAMT='8.6'      |

      #Since Inception Gross Absolute Returns - Primary Benchmark
      | SIFundGrossAbsoluteReturn_1                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossAbsoluteReturn_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and CUM_SI_RETURN_CAMT='10.1'                          |
      | SIFundGrossAbsoluteReturn_2                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossAbsoluteReturn_2 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and CUM_SI_RETURN_CAMT='10.2'                                      |
      | SIFundGrossAbsoluteReturn_3                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossAbsoluteReturn_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and CUM_SI_RETURN_CAMT='10.3'                                      |
      | SIFundGrossAbsoluteReturn_4                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossAbsoluteReturn_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and CUM_SI_RETURN_CAMT='10.4'                                         |
      | SIFundGrossAbsoluteReturn_5                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossAbsoluteReturn_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and CUM_SI_RETURN_CAMT='10.6'                               |

      #Since Inception Gross Absolute Returns - Secondary Benchmark
      | SIFundGrossAbsoluteReturn_6                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossAbsoluteReturn_6 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and CUM_SI_RETURN_CAMT='10.1'                        |
      | SIFundGrossAbsoluteReturn_7                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossAbsoluteReturn_7 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and CUM_SI_RETURN_CAMT='10.2'                                    |
      | SIFundGrossAbsoluteReturn_8                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossAbsoluteReturn_8 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and CUM_SI_RETURN_CAMT='10.3'                                    |
      | SIFundGrossAbsoluteReturn_9                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossAbsoluteReturn_9 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and CUM_SI_RETURN_CAMT='10.4'                                       |
      | SIFundGrossAbsoluteReturn_10                  | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossAbsoluteReturn_10 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'SEBENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and CUM_SI_RETURN_CAMT='10.6'                            |

      #Since Inception Gross Relative Returns - Primary Benchmark
      | SIFundGrossRelativeReturn_1                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossRelativeReturn_1 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFeesOrWthdgTaxes' and CUM_SI_RELV_RETURN_CAMT='11.1'                     |
      | SIFundGrossRelativeReturn_2                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossRelativeReturn_2 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossAllFees' and CUM_SI_RELV_RETURN_CAMT='11.2'                                 |
      | SIFundGrossRelativeReturn_3                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossRelativeReturn_3 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFees' and CUM_SI_RELV_RETURN_CAMT='11.3'                                 |
      | SIFundGrossRelativeReturn_4                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossRelativeReturn_4 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossTWRR' and CUM_SI_RELV_RETURN_CAMT='11.4'                                    |
      | SIFundGrossRelativeReturn_5                   | select CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS SIFundGrossRelativeReturn_5 from ft_w_wcri w where dw_status_num =1 and acct_sok_2 = (select ACCT_SOK from FT_T_WACT where INTRNL_ID1 = 'BENT5178' AND DW_STATUS_NUM=1) and return_typ ='GrossMgtFeesNetTWRR' and CUM_SI_RELV_RETURN_CAMT='11.6'                          |
