package com.eastspring.tom.cart.core;

/**
 *
 * @author Daniel Baktiar
 * @since 2017-09
 */
public enum CartExceptionType {
    UNDEFINED,
    BOOTSTRAP_CONFIG,
    INCOMPLETE_PARAMS,
    INVALID_INVOCATION_PARAMS,
    PROCESSING_FAILED,
    EXPECTED_WEBELEMENT_DOESNT_EXIST,
    ELEMENT_NOT_CLICKABLE,
    ELEMENT_NOT_VISIBLE,
    UNSATISFIED_IMPLICIT_ASSUMPTION,
    UNSUPPORTED_ENCODING,
    NUMERIC_VERIFICATION_FAILED,
    VALIDATION_FAILED,
    VERIFICATION_FAILED,
    INVALID_DATA_TABLE,
    IO_ERROR
}
