Feature: Golden Source Web UI

    Scenario: Open GS web ui menu
        Given I open a web session from URL "http://vsgeisldapp07.pru.intranet.asia:8780/GS"
        When I enter text "test1" into web element with id "j_username"
        And I enter text "test1@123" into web element with id "j_password"
        And I submit the form of the web element with id "login"
        Then I select from GS menu "Security Master::Issue"
        Then I select from GS menu "Security Master::Instrument Group"
        Then I select from GS menu "Security Master::Issue Type"
        Then I select from GS menu "Security Master::Issue Type Group"
        Then I select from GS menu "Security Master::Issue Ratings"
        Then I select from GS menu "Security Master::Issue Rating Opinions"
        Then I select from GS menu "Security Master::Underlying Issue"
        Then I select from GS menu "Security Master::Mortgage Pool Prefix"
        Then I select from GS menu "Security Master::Property Document"
        Then I select from GS menu "Security Master::Request for Issues"
        Then I select from GS menu "Security Master::Vendor Request Schedule"
        Then I select from GS menu "Security Master::Vendor Request Management"
        Then I select from GS menu "Security Master::Issuer"
        Then I select from GS menu "Security Master::Issuer Group"
        Then I select from GS menu "Security Master::Issuance Conflict Match"
        Then I select from GS menu "Security Master::Issuance Likely Match"
        Then I select from GS menu "Security Master::Exclude Criteria"
        Then I select from GS menu "Pricing::Issue Price"
