#https://jira.pruconnect.net/browse/EISAPPDEV-5
#https://collaborate.intranet.asia/pages/viewpage.action?pageId=60792291

# =====================================================================
# Date            JIRA        Comments
# ============    ========    ========
# 06/08/2019      TOM-5032    First Version
# =====================================================================
   # Business Need : As part of factsheets tactical project, reconcilliation
   # of published internal report files from Azure Vs Eagle files to be performed.
# =====================================================================

@ignore_hooks @factsheet_publish_recon  @factsheet_publish_recon_fund_cntry_sec
Feature: Factsheet (CSV files) Reconciliations for AutomatedScripts

  As an User, I expect Factsheet (CSV) files generated by 2 different sources (SRC1 & SRC2) should be same.
  Reconciliation should be successful and if any differences between two files will be captured.

  Scenario: Set up Test data paths and prerequisites

    Given I assign "tests/features/factsheet/publish-recon/test-data/AutomatedScripts/AZURE" to variable "SRC1_TESTDATA_PATH"
    And I assign "tests/features/factsheet/publish-recon/test-data/AutomatedScripts/EAGLE" to variable "SRC2_TESTDATA_PATH"
    And I assign "tests/features/factsheet/publish-recon/test-data/Exceptions" to variable "EXCEPTIONS_PATH"

  Scenario Outline: Reconciliations of Factsheet : Fund Code "<fund_code>" for "<file>"

    Given I capture current time stamp into variable "recon.timestamp"
    And I assign "${SRC1_TESTDATA_PATH}/<fund_code>/<file>" to variable "SRC1_FILE"
    And I assign "${SRC2_TESTDATA_PATH}/<fund_code>/<file>" to variable "SRC2_FILE"
    And I assign "${EXCEPTIONS_PATH}/exceptions_<fund_code>_<file>_${recon.timestamp}.csv" to variable "EXCP_FILE"

    Then I expect reconciliation between generated CSV file "${SRC1_FILE}" and reference CSV file "${SRC2_FILE}" should be successful and exceptions to be written to "${EXCP_FILE}" file

    Examples: Fund Code 500100
      | fund_code | file                |
      | 500100    | TOP10_HOLDINGS.csv  |
      | 500100    | COUNTRY.csv         |
      | 500100    | COUNTRY_DETAILS.csv |
      | 500100    | SECTOR.csv          |
      | 500100    | SECTOR_DETAILS.csv  |


    Examples: Fund Code 500110
      | fund_code | file                |
      | 500110    | TOP10_HOLDINGS.csv  |
      | 500110    | COUNTRY.csv         |
      | 500110    | COUNTRY_DETAILS.csv |
      | 500110    | SECTOR.csv          |
      | 500110    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500120
      | fund_code | file                |
      | 500120    | TOP10_HOLDINGS.csv  |
      | 500120    | COUNTRY.csv         |
      | 500120    | COUNTRY_DETAILS.csv |
      | 500120    | SECTOR.csv          |
      | 500120    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500130
      | fund_code | file                 |
      | 500130    | TOP10_HOLDINGS.csv   |
      | 500130    | COUNTRY.csv          |
      | 500130    | COUNTRY_DETAILS.csv  |
      | 500130    | SECTOR.csv           |
      | 500130    | SECTOR_DETAILS.csv   |
      | 500130    | MATURITY.csv         |
      | 500130    | MATURITY_DETAILS.csv |
      | 500130    | RATINGS.csv          |
      | 500130    | RATINGS_BD.csv       |
      | 500130    | RATINGS_DETAILS.csv  |

    Examples: Fund Code 500140
      | fund_code | file                |
      | 500140    | TOP10_HOLDINGS.csv  |
      | 500140    | COUNTRY.csv         |
      | 500140    | SECTOR.csv          |

    Examples: Fund Code 500210
      | fund_code | file                |
      | 500210    | TOP10_HOLDINGS.csv  |
      | 500210    | COUNTRY.csv         |
      | 500210    | COUNTRY_DETAILS.csv |
      | 500210    | SECTOR.csv          |
      | 500210    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500220
      | fund_code | file                |
      | 500220    | TOP10_HOLDINGS.csv  |
      | 500220    | COUNTRY.csv         |
      | 500220    | COUNTRY_DETAILS.csv |
      | 500220    | SECTOR.csv          |
      | 500220    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500230
      | fund_code | file                |
      | 500230    | TOP10_HOLDINGS.csv  |
      | 500230    | COUNTRY.csv         |
      | 500230    | COUNTRY_DETAILS.csv |
      | 500230    | SECTOR.csv          |
      | 500230    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500235
      | fund_code | file                |
      | 500235    | TOP10_HOLDINGS.csv  |
      | 500235    | COUNTRY.csv         |
      | 500235    | COUNTRY_DETAILS.csv |
      | 500235    | SECTOR.csv          |
      | 500235    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500240
      | fund_code | file                |
      | 500240    | TOP10_HOLDINGS.csv  |
      | 500240    | COUNTRY.csv         |
      | 500240    | COUNTRY_DETAILS.csv |
      | 500240    | SECTOR.csv          |
      | 500240    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500270
      | fund_code | file                |
      | 500270    | TOP10_HOLDINGS.csv  |
      | 500270    | COUNTRY.csv         |
      | 500270    | COUNTRY_DETAILS.csv |
      | 500270    | SECTOR.csv          |
      | 500270    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500280
      | fund_code | file                |
      | 500280    | TOP10_HOLDINGS.csv  |
      | 500280    | COUNTRY.csv         |
      | 500280    | COUNTRY_DETAILS.csv |
      | 500280    | SECTOR.csv          |
      | 500280    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500300
      | fund_code | file                |
      | 500300    | TOP10_HOLDINGS.csv  |
      | 500300    | COUNTRY.csv         |
      | 500300    | COUNTRY_DETAILS.csv |
      | 500300    | SECTOR.csv          |
      | 500300    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500330
      | fund_code | file                |
      | 500330    | TOP10_HOLDINGS.csv  |
      | 500330    | COUNTRY.csv         |
      | 500330    | COUNTRY_DETAILS.csv |
      | 500330    | SECTOR.csv          |
      | 500330    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500331
      | fund_code | file                 |
      | 500331    | TOP10_HOLDINGS.csv   |
      | 500331    | COUNTRY.csv          |
      | 500331    | COUNTRY_DETAILS.csv  |
      | 500331    | SECTOR.csv           |
      | 500331    | SECTOR_DETAILS.csv   |
      | 500331    | MATURITY.csv         |
      | 500331    | MATURITY_DETAILS.csv |
      | 500331    | RATINGS.csv          |
      | 500331    | RATINGS_BD.csv       |
      | 500331    | RATINGS_DETAILS.csv  |

    Examples: Fund Code 500333
      | fund_code | file                |
      | 500333    | TOP10_HOLDINGS.csv  |
      | 500333    | COUNTRY.csv         |
      | 500333    | COUNTRY_DETAILS.csv |
      | 500333    | SECTOR.csv          |
      | 500333    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500335
      | fund_code | file                |
      | 500335    | TOP10_HOLDINGS.csv  |
      | 500335    | COUNTRY.csv         |
      | 500335    | COUNTRY_DETAILS.csv |
      | 500335    | SECTOR.csv          |
      | 500335    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500336
      | fund_code | file                |
      | 500336    | TOP10_HOLDINGS.csv  |
      | 500336    | COUNTRY.csv         |
      | 500336    | COUNTRY_DETAILS.csv |
      | 500336    | SECTOR.csv          |
      | 500336    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500337
      | fund_code | file                |
      | 500337    | TOP10_HOLDINGS.csv  |
      | 500337    | COUNTRY.csv         |
      | 500337    | COUNTRY_DETAILS.csv |
      | 500337    | SECTOR.csv          |
      | 500337    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500420
      | fund_code | file                |
      | 500420    | TOP10_HOLDINGS.csv  |
      | 500420    | COUNTRY.csv         |
      | 500420    | COUNTRY_DETAILS.csv |
      | 500420    | SECTOR.csv          |
      | 500420    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500422
      | fund_code | file                 |
      | 500422    | TOP10_HOLDINGS.csv   |
      | 500422    | COUNTRY.csv          |
      | 500422    | COUNTRY_DETAILS.csv  |
      | 500422    | SECTOR.csv           |
      | 500422    | SECTOR_DETAILS.csv   |
      | 500422    | MATURITY.csv         |
      | 500422    | MATURITY_DETAILS.csv |
      | 500422    | RATINGS.csv          |
      | 500422    | RATINGS_BD.csv       |
      | 500422    | RATINGS_DETAILS.csv  |

    Examples: Fund Code 500480
      | fund_code | file                |
      | 500480    | TOP10_HOLDINGS.csv  |
      | 500480    | COUNTRY.csv         |
      | 500480    | COUNTRY_DETAILS.csv |
      | 500480    | SECTOR.csv          |
      | 500480    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500482
      | fund_code | file                |
      | 500482    | TOP10_HOLDINGS.csv  |
      | 500482    | COUNTRY.csv         |
      | 500482    | COUNTRY_DETAILS.csv |
      | 500482    | SECTOR.csv          |
      | 500482    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500483
      | fund_code | file                |
      | 500483    | TOP10_HOLDINGS.csv  |
      | 500483    | COUNTRY.csv         |
      | 500483    | COUNTRY_DETAILS.csv |
      | 500483    | SECTOR.csv          |
      | 500483    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500508
      | fund_code | file                 |
      | 500508    | TOP10_HOLDINGS.csv   |
      | 500508    | COUNTRY.csv          |
      | 500508    | COUNTRY_DETAILS.csv  |
      | 500508    | SECTOR.csv           |
      | 500508    | SECTOR_DETAILS.csv   |
      | 500508    | MATURITY.csv         |
      | 500508    | MATURITY_DETAILS.csv |
      | 500508    | RATINGS.csv          |
      | 500508    | RATINGS_BD.csv       |
      | 500508    | RATINGS_DETAILS.csv  |

    Examples: Fund Code 500560
      | fund_code | file                |
      | 500560    | TOP10_HOLDINGS.csv  |
      | 500560    | COUNTRY.csv         |
      | 500560    | COUNTRY_DETAILS.csv |
      | 500560    | SECTOR.csv          |
      | 500560    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500570
      | fund_code | file                |
      | 500570    | TOP10_HOLDINGS.csv  |
      | 500570    | COUNTRY.csv         |
      | 500570    | COUNTRY_DETAILS.csv |
      | 500570    | SECTOR.csv          |
      | 500570    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500610
      | fund_code | file                |
      | 500610    | TOP10_HOLDINGS.csv  |
      | 500610    | COUNTRY.csv         |
      | 500610    | COUNTRY_DETAILS.csv |
      | 500610    | SECTOR.csv          |
      | 500610    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500630
      | fund_code | file                |
      | 500630    | TOP10_HOLDINGS.csv  |
      | 500630    | COUNTRY.csv         |
      | 500630    | COUNTRY_DETAILS.csv |
      | 500630    | SECTOR.csv          |
      | 500630    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500640
      | fund_code | file                |
      | 500640    | TOP10_HOLDINGS.csv  |
      | 500640    | COUNTRY.csv         |
      | 500640    | COUNTRY_DETAILS.csv |
      | 500640    | SECTOR.csv          |
      | 500640    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500670
      | fund_code | file                |
      | 500670    | TOP10_HOLDINGS.csv  |
      | 500670    | COUNTRY.csv         |
      | 500670    | COUNTRY_DETAILS.csv |
      | 500670    | SECTOR.csv          |
      | 500670    | SECTOR_DETAILS.csv  |

    Examples: Fund Code 500680
      | fund_code | file                 |
      | 500680    | COUNTRY.csv          |
      | 500680    | COUNTRY_DETAILS.csv  |
      | 500680    | SECTOR.csv           |
      | 500680    | SECTOR_DETAILS.csv   |
      | 500680    | TOP10_HOLDINGS.csv   |
      | 500680    | MATURITY.csv         |
      | 500680    | MATURITY_DETAILS.csv |
      | 500680    | RATINGS.csv          |
      | 500680    | RATINGS_BD.csv       |
      | 500680    | RATINGS_DETAILS.csv  |
