#https://jira.pruconnect.net/browse/EISAPPDEV-5
#https://collaborate.intranet.asia/pages/viewpage.action?pageId=60792291

# =====================================================================
# Date            JIRA        Comments
# ============    ========    ========
# 06/08/2019      TOM-5032    First Version
# =====================================================================
   # Business Need : As part of factsheets tactical project, reconcilliation
   # of published internal report files from Azure Vs Eagle files to be performed.
# =====================================================================

@ignore_hooks @factsheet_publish_recon  @factsheet_publish_recon_ppma
Feature: Factsheet (CSV files) Reconciliations for PPMA

  As an User, I expect Factsheet (CSV) files generated by 2 different sources (SRC1 & SRC2) should be same.
  Reconciliation should be successful and if any differences between two files will be captured.

  Scenario: Set up Test data paths and prerequisites

    Given I assign "tests/features/factsheet/publish-recon/test-data/PPMA/AZURE" to variable "SRC1_TESTDATA_PATH"
    And I assign "tests/features/factsheet/publish-recon/test-data/PPMA/EAGLE" to variable "SRC2_TESTDATA_PATH"
    And I assign "tests/features/factsheet/publish-recon/test-data/Exceptions" to variable "EXCEPTIONS_PATH"

  Scenario Outline: Reconciliations of Factsheet : Fund Code "<fund_code>" for "<file>"

    Given I capture current time stamp into variable "recon.timestamp"
    And I assign "${SRC1_TESTDATA_PATH}/<fund_code>/<file>" to variable "SRC1_FILE"
    And I assign "${SRC2_TESTDATA_PATH}/<fund_code>/<file>" to variable "SRC2_FILE"
    And I assign "${EXCEPTIONS_PATH}/exceptions_<fund_code>_<file>_${recon.timestamp}.csv" to variable "EXCP_FILE"

    Then I expect reconciliation between generated CSV file "${SRC1_FILE}" and reference CSV file "${SRC2_FILE}" should be successful and exceptions to be written to "${EXCP_FILE}" file

    Examples: Fund Code 500160
      | fund_code | file               |
      | 500160    | TOP10_HOLDINGS.csv |
      | 500160    | MATURITY.csv       |
      | 500160    | RATINGS.csv        |
      | 500160    | RATINGS_BD.csv     |
      | 500160    | SECTOR.csv         |

    Examples: Fund Code 500170
      | fund_code | file               |
      | 500170    | TOP10_HOLDINGS.csv |
      | 500170    | MATURITY.csv       |
      | 500170    | RATINGS.csv        |
      | 500170    | RATINGS_BD.csv     |
      | 500170    | SECTOR.csv         |

    Examples: Fund Code 500180
      | fund_code | file               |
      | 500180    | TOP10_HOLDINGS.csv |
      | 500180    | MATURITY.csv       |
      | 500180    | RATINGS.csv        |
      | 500180    | RATINGS_BD.csv     |
      | 500180    | SECTOR.csv         |

    Examples: Fund Code 500430
      | fund_code | file               |
      | 500430    | TOP10_HOLDINGS.csv |
      | 500430    | MATURITY.csv       |
      | 500430    | RATINGS.csv        |
      | 500430    | RATINGS_BD.csv     |
      | 500430    | SECTOR.csv         |

    Examples: Fund Code 500440
      | fund_code | file               |
      | 500440    | TOP10_HOLDINGS.csv |
      | 500440    | MATURITY.csv       |
      | 500440    | RATINGS.csv        |
      | 500440    | RATINGS_BD.csv     |
      | 500440    | SECTOR.csv         |

    Examples: Fund Code 500600
      | fund_code | file               |
      | 500600    | TOP10_HOLDINGS.csv |
      | 500600    | MATURITY.csv       |
      | 500600    | RATINGS.csv        |
      | 500600    | RATINGS_BD.csv     |
      | 500600    | SECTOR.csv         |

    Examples: Fund Code 500700
      | fund_code | file               |
      | 500700    | TOP10_HOLDINGS.csv |
      | 500700    | MATURITY.csv       |
      | 500700    | RATINGS.csv        |
      | 500700    | RATINGS_BD.csv     |
      | 500700    | SECTOR.csv         |